ports:
  - port: 8000
    name: Frontend
    onOpen: open-preview

tasks:
  # https://github.com/gitpod-io/gitpod/issues/666#issuecomment-534347856
  - before: >
      [[ ! -z ${GNUGPG}  ]] &&
      cd ~ &&
      rm -rf .gnupg &&
      echo ${GNUGPG} | base64 -d | tar --no-same-owner -xzvf -
    name: signed terminal
    init: >
      [[ ! -z ${GNUGPG_KEY}  ]] &&
      git config --global commit.gpgsign true &&
      git config --global user.signingkey ${GNUGPG_KEY}
    command: >
      cd $GITPOD_REPO_ROOT &&
      yarn --version
  - init: yarn install
    name: frontend
    command: >
      yarn run start
