#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/
# https://microbadger.com/labels

docker build \
    --build-arg "VCS_REF=${SOURCE_COMMIT}" \
    --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
    -f "$DOCKERFILE_PATH" \
    -t "$IMAGE_NAME" .
