#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

# Legacy
#docker build \
#    --build-arg "VCS_REF=${SOURCE_COMMIT}" \
#    --build-arg "BUILD_DATE=${BUILD_DATE}" \
#    --no-cache \
#    -f "$DOCKERFILE_PATH" \
#    -t "${IMAGE_NAME}" ${DOCKER_CLI_TAGS} .

docker buildx build \
    --build-arg "VCS_REF=${SOURCE_COMMIT}" \
    --build-arg "BUILD_DATE=${BUILD_DATE}" \
    --builder "buildx_build_${SOURCE_COMMIT}" \
    --platform "${PLATFORMS}" \
    --no-cache \
    -f "$DOCKERFILE_PATH" \
    -t "${IMAGE_NAME}" ${DOCKER_CLI_TAGS} .
