#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker buildx ls
docker buildx inspect "buildx_${SOURCE_COMMIT}"

docker buildx stop "buildx_${SOURCE_COMMIT}"
docker buildx rm "buildx_${SOURCE_COMMIT}"
