#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker buildx ls
docker buildx inspect "buildx_build_${SOURCE_COMMIT}"

docker buildx stop "buildx_build_${SOURCE_COMMIT}"
docker buildx rm "buildx_build_${SOURCE_COMMIT}"
