#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker buildx ls

docker buildx create \
    --platform "${PLATFORMS}" \
    --name "buildx_${SOURCE_COMMIT}" \
    --use

docker buildx inspect "buildx_${SOURCE_COMMIT}"
