#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker version
docker buildx version

docker buildx ls

docker buildx create \
    --platform "${PLATFORMS}" \
    --name "buildx_build_${SOURCE_COMMIT}" \
    --use

docker buildx inspect "buildx_build_${SOURCE_COMMIT}"
