#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

# Copy the files
template="Dockerfile.template"
cp "$template" "$DOCKERFILE_PATH"

# Replace the variables.
sed -ri -e '
    s/%%ARCHI%%/'"$ARCHI"'/g;
    s/%%VARIANT%%/'"$VARIANT"'/g;
' "$DOCKERFILE_PATH"
