#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker-compose version

if [ ! -f '.env' ] &&  [ -f '.env_template' ]; then
    echo 'Init docker compose environment variables...'
    cp .env_template .env.tmp

    mv .env.tmp .env
fi

#echo 'Preparing persisted data...'
#mkdir -p "${APP_HOME:-.docker/app}"
#chown 777 "${APP_HOME:-.docker/app}"
