#!/bin/bash

# Custom script to run locally DockerHub hooks
# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

echo "Custom script to run locally DockerHub hooks..."
set -e

export SOURCE_BRANCH
SOURCE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
export SOURCE_COMMIT
SOURCE_COMMIT=$(git rev-parse --short HEAD)
export COMMIT_MSG
COMMIT_MSG=$(git log -1 --format=%s)
export BUILD_DATE
BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

export PLATFORMS
PLATFORMS=${2:-linux/amd64}

export DOCKER_REPO=${DOCKER_REPO:-monogramm/autodiscover-email-settings}
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_TAG=${DOCKER_TAG:-latest}

if [ -n "${DOCKER_REGISTRY}" ]; then
    export DOCKER_BASE_IMAGE=${DOCKER_REGISTRY}/${DOCKER_REPO}
else
    export DOCKER_BASE_IMAGE=${DOCKER_REPO}
fi
export IMAGE_NAME=${DOCKER_BASE_IMAGE}:${DOCKER_TAG}

export DOCKER_CLI_TAGS
DOCKER_CLI_TAGS="-t ${DOCKER_BASE_IMAGE}:${SOURCE_COMMIT} "

if [ -f ./.dockertags ]; then
    for tag in $(cat ./.dockertags); do
        if [ ! "${tag}" = "${DOCKER_TAG}" ]; then
            DOCKER_CLI_TAGS="${DOCKER_CLI_TAGS} -t ${DOCKER_BASE_IMAGE}:${tag} "
        fi
    done
fi

# Execute hooks in given order
IFS=',' read -ra STEPS <<< "${1:-build,test}"
for step in "${STEPS[@]}"
do
    for hook in "pre_${step}" "${step}" "post_${step}"; do
        if [ -f "./hooks/${hook}" ]; then
            echo "Executing ${hook} hook..."
            "./hooks/${hook}"
        fi
    done
done

echo "DockerHub hooks finished"
