#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ "${DOCKERFILE_PATH}" = "Dockerfile.develop" ] || [ "${DOCKERFILE_PATH}" = "Dockerfile.gitpod" ]; then
    echo "No tests (yet) for ${DOCKERFILE_PATH} images."
    exit 0
fi

for file in docker-compose*.test.yml; do

    echo "Starting Test in ${file} for platform ${PLATFORM}..."

    # Build test container
    docker-compose --ansi never -f "${file}" build sut
    # Test container run
    docker-compose --ansi never -f "${file}" up -d --no-build && sleep 60
    docker-compose --ansi never -f "${file}" logs -f "sut"
    docker-compose --ansi never -f "${file}" ps
    docker-compose --ansi never -f "${file}" logs --no-color "autodiscover"
    docker-compose --ansi never -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --ansi never -f "${file}" down

    # Test container restart
    docker-compose --ansi never -f "${file}" up -d && sleep 60
    docker-compose --ansi never -f "${file}" logs -f "sut"
    docker-compose --ansi never -f "${file}" ps
    docker-compose --ansi never -f "${file}" logs --no-color "autodiscover"
    docker-compose --ansi never -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --ansi never -f "${file}" down -v

done
