
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64', 'arm32v6', 'arm32v7', 'arm64v8']
        variant: ['lts-alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI build AMD hooks
        id: docker_build_amd
        if: matrix.arch == 'amd64'
        run: |
          # Export variables to tag against GitHub Container Registry
          #export DOCKER_REGISTRY=ghcr.io
          #export DOCKER_REPO=${{ github.repository }}
          ./hooks/run build ${{ matrix.arch }} ${{ matrix.variant }}

      - name: Execute CI build ARM hooks
        id: docker_build_arm
        uses: pguyot/arm-runner-action@v2
        if: matrix.arch == 'arm32v6' || matrix.arch == 'arm32v7' || matrix.arch == 'arm64v8'
        run: |
          # Export variables to tag against GitHub Container Registry
          #export DOCKER_REGISTRY=ghcr.io
          #export DOCKER_REPO=${{ github.repository }}
          ./hooks/run build ${{ matrix.arch }} ${{ matrix.variant }}

      - name: Display docker images
        run: docker images

      - name: Execute CI test AMD hooks
        id: docker_test_amd
        if: matrix.arch == 'amd64'
        run: |
          ./hooks/run test

      - name: Execute CI test hooks
        id: docker_test_arm
        uses: pguyot/arm-runner-action@v2
        if: matrix.arch == 'arm32v6' || matrix.arch == 'arm32v7' || matrix.arch == 'arm64v8'
        run: |
          ./hooks/run test

      - name: Execute CI push hooks
        id: docker_push
        if: ${{ github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) }}
        run: |
          # Export variables to login and push to DockerHub Registry
          export DOCKER_LOGIN=${{ secrets.DOCKERHUB_REGISTRY_LOGIN }}
          export DOCKER_PASSWORD=${{ secrets.DOCKERHUB_REGISTRY_TOKEN }}
          ./hooks/run push
          # Export variables to login and push to GitHub Container Registry
          #export DOCKER_REGISTRY=ghcr.io
          #export DOCKER_LOGIN=${{ github.repository_owner }}
          #export DOCKER_PASSWORD=${{ secrets.GITHUB_REGISTRY_TOKEN }}
          #./hooks/run push
