name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve author data
        id: author
        run: |
          AUTHOR=$(curl -sSL ${{ github.event.repository.owner.url }} | jq -r '.name')
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Set up environment
        run: |
          echo "TAG_NAME=" >> $GITHUB_ENV
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAG_NAME=main" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TAG_NAME=master" >> $GITHUB_ENV
          fi
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.TAG_NAME }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-
          labels: |
            org.opencontainers.image.authors=${{ env.AUTHOR }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}

      - name: Build and push container image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            COMMIT=${{ github.sha }}
